//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ModuleManager.rc 使用
//
#define IDC_SERVICE_ATTRIB              3
#define IDD_SERVER_ITEM                 129
#define IDD_SERVER_WIZARD_MAIN          137
#define IDD_SERVER_OPTION_1             148
#define IDD_SERVER_WIZARD_1             150
#define IDD_SERVER_OPTION_3             151
#define IDC_LOAD_SERVER                 1000
#define IDC_SERVER_NAME                 1001
#define IDC_MODULE_LIST                 1002
#define IDC_NODE_ID                     1007
#define IDC_SERVER_TYPE                 1008
#define IDC_MIN_ENTER_MEMBER            1009
#define IDC_SERVER_KIND                 1009
#define IDC_TABLE_COUNT                 1010
#define IDC_MAX_ENTER_MEMBER            1010
#define IDC_MAX_PLAYER                  1011
#define IDC_SERVER_PORT                 1012
#define IDC_SERVER_LIST                 1012
#define IDC_SORT_ID                     1013
#define IDC_CELL_SCORE                  1014
#define IDC_RELOAD_LIST                 1014
#define IDC_MODULE_DESCRIBE             1014
#define IDC_SERVER_PORT2                1015
#define IDC_SERVER_PASSWD               1015
#define IDC_CHAIR_COUNT                 1016
#define IDC_MAX_ENTER_MEMBER7           1016
#define IDC_SERVER_PASSWD2              1016
#define IDC_DATABASE_ADDR               1017
#define IDC_DELETE_SERVER               1018
#define IDC_DATABASE_NAME               1018
#define IDC_SERVER_TYPE2                1019
#define IDC_PESONAL_SQL_TYPE            1019
#define IDC_SET_COUNT                   1020
#define IDC_SERVICE_DLL_NAME            1021
#define IDC_GAME_INFOMATION             1021
#define IDC_KIND_ID                     1022
#define IDC_CLIENT_EXE_NAME             1023
#define IDC_GAME_NAME                   1024
#define IDC_COMBO_SERVER_LEVEL          1033
#define IDC_RESTRICT_SCORE              1026
#define IDC_REVENUE_RATIO               1027
#define IDC_MIN_ENTER_SCORE             1027
#define IDC_REVENUE_RADIO               1027
#define IDC_MAX_ENTER_SCORE             1028
#define IDC_SERVICE_REVENUE             1028
#define IDC_SERVICE_SCORE               1028
#define IDC_MIN_TABLE_SCORE             1029
#define IDC_MAX_TABLE_SCORE             1030
#define IDC_AV_SERVER_PORT              1031
#define IDC_LAST                        1065
#define IDC_NEXT                        1067
#define IDC_ITEM_FRAME                  1072
#define IDC_FINISH                      1076
#define IDC_PROMPT                      9000
#define IDD_SERVER_OPTION_2             9001
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDC_CHECK_REVIVE_ENABLED        9001
#define IDD_SERVER_WIZARD_2             9002
#define IDC_RECORD_GAME_SCORE           9002
#define IDC_CHECK_SAFECARD_ENABLED      9002
#define IDC_ALLOW_LAST_SAMETABLE        9002
#define IDC_RECORD_GAME_TRACK           9003
#define IDD_SERVER_OPTION_4             9003
#define IDC_ALLOW_SAME_ADDRESS          9003
#define IDC_FORFEND_ROOM_CHAT           9004
#define IDC_CHECK_MEMBER_ORDER          9004
#define IDC_FORFEND_WISPER_CHAT         9005
#define IDD_SERVER_OPTION_5             9005
#define IDC_FORFEND_GAME_CHAT           9006
#define IDD_SERVER_MATCH                9006
#define IDC_ALLOW_DYNAMIC_JOIN          9007
#define IDC_FORFEND_GAME_LOOKON         9008
#define IDD_MATCH_WIZARD                9008
#define IDC_FORFEND_GAME_ENTER          9009
#define IDD_MATCH_WIZARD_1              9009
#define IDC_CHECK_MATCH_USER            9009
#define IDC_EDIT_COUNT_INNINGS          9009
#define IDC_PLAY_COUNT                  9009
#define IDC_ALLOW_OFFLINE_TRUSTEE       9010
#define IDD_MATCH_WIZARD_2              9010
#define IDC_CHECK_EXPERIENCE            9010
#define IDC_SWITCH_TABLE_COUNT          9010
#define IDC_ALLOW_AVERT_DEBUG_MODE      9011
#define IDC_CHECK_SIGNUP_FEE            9011
#define IDC_MIN_PLAYCOUNT               9011
#define IDD_MATCH_LOCKTIME              9011
#define IDC_ALLOW_ANDROID_ATTEND        9012
#define IDC_MIN_MATCH_USER              9012
#define IDC_INITIAL_BASE                9012
#define IDD_MATCH_IMMEDIATE             9012
#define IDC_FORFEND_ROOM_ENTER          9013
#define IDC_RADIO_SINGLE_TURN           9013
#define IDC_RADIO_TOTAL_GRADES          9013
#define IDD_MAX_SIGNUP_USER             9013
#define IDC_START_USERCOUNT             9013
#define IDD_MATCH_DISTRIBUTE            9013
#define IDC_FORFEND_WISPER_ON_GAME      9014
#define IDC_RADIO_TOTAL_RANKING         9014
#define IDD_MATCH_SIGNUP1               9014
#define IDC_RADIO_SPECIALLY_GRADES      9014
#define IDC_MAX_PLAYCOUNT               9014
#define IDC_TAB_CTRL                    9015
#define IDC_FORFEND_GAME_RULE           9015
#define IDC_RADIO_NOAMAL                9015
#define IDD_MATCH_SIGNUP2               9015
#define IDC_RADIO_SERVER                9015
#define IDC_RADIO_BEST_GRADES           9015
#define IDD_END_DELAY_TIME              9015
#define IDC_ANDROID_USERCOUNT           9015
#define IDC_PARTAKE_MIN_GAMEUSER        9015
#define IDC_FORFEND_LOCK_TABLE          9016
#define IDC_RADIO_WEBSITE               9016
#define IDC_RADIO_AVERAGE_GRADES        9016
#define IDD_MATCH_RANKING_MODE          9016
#define IDC_ANDROID_DELAYTIME           9016
#define IDC_PARTAKE_MAX_GAMEUSER        9016
#define IDC_RADIO_MEMBER_V1             9016
#define IDC_INITIAL_BASE_LOCK           9016
#define IDC_FORFEND_SAVE_IN_GAME        9017
#define IDC_RADIO_AVERAGEEX_GRADES      9017
#define IDC_RADIO_MEMBER_V2             9017
#define IDC_FORFEND_SAVE_IN_ROOM        9018
#define IDC_RADIO_MEMBER_V3             9018
#define IDD_SERVER_OPTION_6             9018
#define IDC_ALLOW_ANDROID_SIMULATE      9019
#define IDC_RADIO_GOLD                  9019
#define IDC_RADIO_MEMBER_V4             9019
#define IDD_MATCH_ANDROID_BASE          9019
#define IDC_RADIO_MEDAL                 9020
#define IDC_RADIO_MEMBER_V5             9020
#define IDD_MATCH_ANDROID_JOIN          9020
#define IDC_DYNAMIC_CELL_SCORE          9021
#define IDC_GAME_ID                     9021
#define IDC_RADIO_MEMBER_V6             9021
#define IDC_DISTRIBUTE_ALLOW            9022
#define IDC_STATIC_REVENUE_SERVICE      9022
#define IDC_RADIO_MEMBER_V7             9022
#define IDC_DISTRIBUTE_LAST_TABLE       9023
#define IDC_DISTRIBUTE_IMMEDIATE        9024
#define IDC_RADIO2                      9024
#define IDC_SERVICE_SCORE_RADIO         9024
#define IDC_SERVICE_RATIO_RADIO         9300
#define IDC_RADIO_JOIN_GAME             9024
#define IDC_MIN_DISTRIBUTE_USER         9025
#define IDC_MATCH_LIST                  9025
#define IDC_PERSONAL_ROOM_TAX           9025
#define IDC_MAX_DISTRIBUTE_USER         9026
#define IDC_LOAD_MATCH                  9026
#define IDC_SERVER_SUPORT_MOBILE        9026
#define IDC_STATIC_SQL_OPTION           9026
#define IDC_DISTRIBUTE_TIME_SPACE       9027
#define IDC_DELETE_MATCH                9027
#define IDC_CHECK2                      9027
#define IDC_SERVER_SUPORT_PC            9027
#define IDC_DISTRIBUTE_DRAW_COUNT       9028
#define IDC_SERVER_SUPORT_VIDEO         9028
#define IDC_DISTRIBUTE_SAME_ADDRESS     9029
#define IDC_RADIO_NOT_JOIN_GAME         9029
#define IDC_SERVER_SUPORT_GROUP         9029
#define IDC_DISTRIBUTE_START_DELAY      9030
#define IDC_DISTRIBUTE_START_MIN_USER   9030
#define IDC_EDIT_MIN_PEOPLE             9030
#define IDC_DISTRIBUTE_DRAW_COUNT3      9031
#define IDC_DISTRIBUTE_START_MAX_USER   9031
#define IDC_CREATE_MATCH                9031
#define IDC_EDIT_MAX_PEOPLE             9031
#define IDC_OPTION_MATCH                9032
#define IDC_RADIO_COST_BEAN             9032
#define IDC_RADIO_COST_ROOM_CARD        9033
#define IDC_EDIT_MAX_TURN               9034
#define IDC_COMBO_MATCH_TYPE            9035
#define IDC_EDIT_MAX_MINUTE             9035
#define IDC_EDIT_MAX_CELL               9036
#define IDC_EDIT_MAX_ROOM               9037
#define IDC_EDIT_DISSUME_TIME_AFTER_BEGIN 9038
#define IDC_MATCH_START_DATE            9039
#define IDC_STATIC_DISSUME_TIME_OFFLINE 9039
#define IDC_MATCH_END_DATE              9040
#define IDC_EDIT_DISSUME_TIME_OFFLINE   9040
#define IDC_MATCH_START_TIME            9041
#define IDC_EDIT_DISSUME_TIME_BEFORE_BEGIN 9041
#define IDC_MATCH_END_TIME              9042
#define IDC_EDIT_FEE_BEAN_OR_ROOMCARD   9042
#define IDC_LIST_REWARD                 9043
#define IDC_SIGNUP_END_DATE             9043
#define IDC_EDIT_INISCORE               9043
#define IDC_RADIO1                      9043
#define IDC_RADIO_LEVEL_0               9043
#define IDC_EDIT_MATCHNAME              9044
#define IDC_ADD_REWARD                  9044
#define IDC_SIGNUP_END_TIME             9044
#define IDC_EDIT_DISSUME_TIME_BEFORE_BEGIN2 9044
#define IDC_EDIT_DISSUME_TIME_AFTER_CREATE 9044
#define IDC_SIGNUP_START_DATE           9045
#define IDC_RADIO3                      9045
#define IDC_RADIO                       9045
#define IDC_RADIO_LEVEL_1               9045
#define IDC_EDIT_MATCH_NAME             9046
#define IDC_SIGNUP_START_TIME           9046
#define IDC_RADIO4                      9046
#define IDC_RADIO_LEVEL_2               9046
#define IDC_EDIT_SIGNUP_FEE             9047
#define IDC_RADIO5                      9047
#define IDC_RADIO_LEVEL_3               9047
#define IDC_DISTRIBUTE_MINCOUNT         9048
#define IDC_RADIO6                      9048
#define IDC_RADIO_LEVEL_4               9048
#define IDC_DISTRIBUTE_TIMESPACE        9049
#define IDC_RADIO7                      9049
#define IDC_RADIO_LEVEL_5               9049
#define IDC_MATCH_OPTION_FRAME          9050
#define IDC_EDIT_TURN_NUM               9050
#define IDC_RANKID_START                9051
#define IDC_EDIT_CREATE_FEE             9051
#define IDC_REWARD_GOLD                 9052
#define IDC_EDIT_ROOM_INISCORE          9052
#define IDC_RANKID_END                  9053
#define IDC_EDIT_TURN_NUM2              9053
#define IDC_INIT_SCORE                  9054
#define IDC_EDIT_CREATE_FEE2            9054
#define IDC_REWARD_INGOT                9055
#define IDC_CULL_SCORE                  9055
#define IDC_EDIT_ROOM_INISCORE2         9055
#define IDC_REVIVE_TIMES                9056
#define IDC_EDIT_TURN_NUM3              9056
#define IDC_REVIVE_FEE                  9057
#define IDC_REWARD_EXPERIENCE           9057
#define IDC_EDIT_CREATE_FEE3            9057
#define IDC_SAFECARD_FEE                9058
#define IDC_EDIT_ROOM_INISCORE3         9058
#define IDC_EDIT_TURN_NUM4              9059
#define IDC_COMBO_FROM_MATCH            9060
#define IDC_EDIT_CREATE_FEE4            9060
#define IDC_DATE_MATCH_START            9061
#define IDC_EDIT_ROOM_INISCORE4         9061
#define IDC_DATE_MATCH_END              9062
#define IDC_EDIT_TURN_NUM5              9062
#define IDC_EDIT_SINGLE_RANK            9063
#define IDC_EDIT_CREATE_FEE5            9063
#define IDC_EDIT_TOTAL_RANK             9064
#define IDC_EDIT_ROOM_INISCORE5         9064
#define IDC_EDIT_EXPERIENCE             9065
#define IDC_EDIT_CREATE_AA_FEE6         9065
#define IDC_COMBO_FROM_MATCH2           9065
#define IDC_EDIT_CREATE_AA_FEE7         9066
#define IDC_DATE_MATCH_START2           9066
#define IDC_COMBO_MATCH_MODE            9067
#define IDC_MODIFY_REWARD               9067
#define IDC_EDIT_CREATE_AA_FEE8         9067
#define IDC_DATE_MATCH_END2             9067
#define IDC_MATCH_FRAME                 9068
#define IDC_DELETE_REWARD               9068
#define IDC_EDIT_CREATE_AA_FEE9         9068
#define IDC_EDIT_SINGLE_RANK2           9068
#define IDC_EDIT_CREATE_AA_FEE10        9069
#define IDC_MODIFY_REWARD2              9069
#define IDC_EDIT_BEGIN_FREE_TIME        9070
#define IDC_DELETE_REWARD2              9070
#define IDC_EDIT_ROOM_INISCORE7         9071
#define IDC_EDIT_END_FREE_TIME          9071
#define IDC_RADIO_QUANSHU2              9072
#define IDC_RADIO_SCORE_MODE            9072
#define IDC_EDIT_MIN_CELLSCORE          9072
#define IDC_COMBO_SELECT_MODE1          9073
#define IDC_COMBO_SELECT_MODE2          9074
#define IDC_EDIT_ANDROID_FULL_TIME      9074
#define IDC_COMBO_SELECT_MODE3          9075
#define IDC_EDIT_TOTAL_SECTION          9075
#define IDC_COMBO_SELECT_MODE4          9076
#define IDC_COMBO_SELECT_MODE5          9077
#define IDC_CHECK_ANDROID_WIN           9077
#define IDC_EDIT_CELLSCORE              9078
#define IDC_EDIT_MAX_CELLSCORE          9078
#define IDC_EDIT_DISSUME_TIME_AFTER_CREATE2 9079
#define IDC_EDIT_TIME_RESPOND_DISMISS   9079
#define IDC_STATIC_SHU1                 9080
#define IDC_STATIC_SHU2                 9081
#define IDC_EDIT_ANDROID_MAX_COUNT      9081
#define IDC_STATIC_SHU3                 9082
#define IDC_EDIT_INIT_ANDROID_MIN       9082
#define IDC_STATIC_SHU4                 9083
#define IDC_EDIT_INIT_ANDROID_MAX       9083
#define IDC_STATIC_SHU5                 9084
#define IDC_EDIT_NO1_RATIO1             9084
#define IDC_EDIT12                      9085
#define IDC_EDIT_NO1_RATIO2             9085
#define IDC_EDIT_NO1_RATIO3             9086
#define IDC_EDIT_PROMOTION1             9087
#define IDC_EDIT_PROMOTION2             9088
#define IDC_BUTTON1                     9088
#define IDC_EDIT_PROMOTION3             9089
#define IDC_BUTTON2                     9089
#define _TIME                           9089
#define IDC_EDIT_ATUO_READY_TIME        9089
#define IDC_EDIT_PROMOTION4             9090
#define IDC_BUTTON3                     9090
#define IDC_EDIT_PROMOTION5             9091
#define IDC_BUTTON4                     9091
#define IDC_EDIT_PROMOTION6             9092
#define IDC_EDIT_PROMOTION7             9093
#define IDC_EDIT_PROMOTION8             9094
#define IDC_EDIT_PROMOTION9             9095
#define IDC_EDIT_PROMOTION10            9096
#define IDC_INITIAL_SCORE               9100
#define IDC_INITIAL_SCORE1              9101
#define IDC_INITIAL_SCORE2              9102
#define IDC_INITIAL_SCORE3              9103
#define IDC_INITIAL_SCORE4              9104
#define IDC_INITIAL_SCORE5              9105
#define IDC_INITIAL_SCORE6              9106
#define IDC_INITIAL_SCORE7              9107
#define IDC_INITIAL_SCORE8              9108
#define IDC_INITIAL_SCORE9              9109
#define IDC_INITIAL_SCORE10             9110
#define IDC_COMBO_PROMOTION1            9111
#define IDC_COMBO_PROMOTION2            9112
#define IDC_COMBO_PROMOTION3            9113
#define IDC_COMBO_PROMOTION4            9114
#define IDC_COMBO_PROMOTION5            9115
#define IDC_COMBO_PROMOTION6            9116
#define IDC_COMBO_PROMOTION7            9117
#define IDC_COMBO_PROMOTION8            9118
#define IDC_COMBO_PROMOTION9            9119
#define IDC_COMBO_PROMOTION10           9120
#define IDC_COMBO_JUSHU1                9121
#define IDC_COMBO_JUSHU2                9122
#define IDC_COMBO_JUSHU3                9123
#define IDC_COMBO_JUSHU4                9124
#define IDC_COMBO_JUSHU5                9125
#define IDC_COMBO_JUSHU6                9126
#define IDC_COMBO_JUSHU7                9127
#define IDC_COMBO_JUSHU8                9128
#define IDC_COMBO_JUSHU9                9129
#define IDC_COMBO_JUSHU10               9130
#define IDC_RADIO_RESET2                9131
#define IDC_RADIO_RESET3                9132
#define IDC_RADIO_RESET4                9133
#define IDC_RADIO_RESET5                9134
#define IDC_RADIO_RESET6                9135
#define IDC_RADIO_RESET7                9136
#define IDC_RADIO_RESET8                9137
#define IDC_RADIO_RESET9                9138
#define IDC_RADIO_RESET10               9139
#define IDC_RADIO_CUMULATIVE2           9140
#define IDC_RADIO_CUMULATIVE3           9141
#define IDC_RADIO_CUMULATIVE4           9142
#define IDC_RADIO_CUMULATIVE5           9143
#define IDC_RADIO_CUMULATIVE6           9144
#define IDC_RADIO_CUMULATIVE7           9145
#define IDC_RADIO_CUMULATIVE8           9146
#define IDC_RADIO_CUMULATIVE9           9147
#define IDC_RADIO_CUMULATIVE10          9148
#define IDC_EDIT_SECTION1               9149
#define IDC_EDIT_SECTION2               9150
#define IDC_EDIT_SECTION3               9151
#define IDC_EDIT_SECTION4               9152
#define IDC_EDIT_SECTION5               9153
#define IDC_EDIT_SECTION6               9154
#define IDC_EDIT_SECTION7               9155
#define IDC_EDIT_SECTION8               9156
#define IDC_EDIT_SECTION9               9157
#define IDC_EDIT_SECTION10              9158
#define IDC_STATIC_PERSONAL_GROUP       9200
#define IDC_STATIC_MIN_ENTER_SCORE      9201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9001
#define _APS_NEXT_COMMAND_VALUE         3277
#define _APS_NEXT_CONTROL_VALUE         9090
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
