//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ClientDebug.rc 使用
//
#define IDD_DIALOG_MAIN                 3100
#define IDD_CUSTOM_GENERAL              3101
#define IDD_CUSTOM_ADVANCED             3102
#define IDD_CUSTOM_TRACELOG             3103
#define IDC_STATIC_SHOW                 3104
#define IDC_TAB_CUSTOM                  3105
#define IDC_EDIT_STATISTIC_SYSWIN       4000
#define IDC_EDIT_STATISTIC_SERVICE      4001
#define IDC_STATIC_CUR_ANCHOU_RATE      4002
#define IDC_EDIT_CONFIG_ANCHOU_RATE     4003
#define IDC_STATIC_CUR_ANCHOU_TOTAL     4004
#define IDC_BUTTON_ANCHOU               4005
#define IDC_STATIC_CUR_MOSGOLD_STORAGE  4006
#define IDC_STATIC_CUR_MOSGOLD_RATE     4007
#define IDC_STATIC_CUR_MOSGOLD_DISRATE  4008
#define IDC_STATIC_CUR_MOSGOLD_STORAGERATE 4009
#define IDC_EDIT_CONFIG_MOSGOLD_RATE    4010
#define IDC_EDIT_CONFIG_MOSGOLD_DISRATE 4011
#define IDC_EDIT_CONFIG_MOSGOLDSTORAGE_RATE  4012
#define IDC_BUTTON_MOSGOLD              4013
#define IDC_STATIC_CUR_SYSCTRL_SYSSTORAGE 4014
#define IDC_STATIC_CUR_SYSCTRL_PLAYERSTORAGE 4015
#define IDC_STATIC_CUR_SYSCTRL_PARAMETER_K 4016
#define IDC_STATIC_CUR_SYSCTRL_SYSSTORAGE_RESETRATE 4017
#define IDC_STATIC_CUR_SYSCTRL_WINRATE  4018
#define IDC_STATIC_CUR_SYSCTRL_RESETCOUNT 4019
#define IDC_STATIC_CUR_SYSCTRL_SYSWIN   4020
#define IDC_EDIT_CONFIG_SYSCTRL_SYSSTORAGE 4021
#define IDC_EDIT_CONFIG_SYSCTRL_PLAYERSTORAGE 4022
#define IDC_EDIT_CONFIG_SYSCTRL_PARAMETER_K 4023
#define IDC_EDIT_CONFIG_SYSCTRL_SYSSTORAGE_RESETRATE 4024
#define IDC_BUTTON_SYSCTRL              4025
#define IDC_STATIC_CUR_ROOMCTRL_SYSSTORAGE 4026
#define IDC_STATIC_CUR_ROOMCTRL_PLAYERSTORAGE 4027
#define IDC_STATIC_CUR_ROOMCTRL_PARAMETER_K 4028
#define IDC_STATIC_CUR_ROOMCTRL_SYSSTORAGE_RESETRATE 4029
#define IDC_STATIC_CUR_ROOMCTRL_WINRATE 4030
#define IDC_EDIT_CONFIG_ROOMCTRL_SYSSTORAGE 4031
#define IDC_EDIT_CONFIG_ROOMCTRL_PLAYERSTORAGE 4032
#define IDC_EDIT_CONFIG_ROOMCTRL_PARAMETER_K 4033
#define IDC_EDIT_CONFIG_ROOMCTRL_SYSSTORAGE_RESETRATE 4034
#define IDC_BUTTON_ROOMCTRL             4035
#define IDC_LIST_CUR_ROOMCTRL_INFO      4036
#define IDC_STATIC_CUR_ROOMCTRL_SYSWIN  4037
#define IDC_BUTTON_CANCEL_ROOMCTRL      4038
#define IDC_EDIT_ADVANCED_AREALONG_INSCORE 4500
#define IDC_EDIT_ADVANCED_AREAPING_INSCORE 4501
#define IDC_EDIT_ADVANCED_AREAHU_INSCORE 4502
#define IDC_BUTTON_ADVANCED_AREALONG    4503
#define IDC_BUTTON_ADVANCED_AREAPING    4504
#define IDC_BUTTON_ADVANCED_AREAHU      4505
#define IDC_STATIC_AREACTRL_ID          4506
#define IDC_STATIC_AREACTRL_POS         4507
#define IDC_STATIC_AREACTRL_CONFIGCOUNT 4508
#define IDC_STATIC_AREACTRL_CURCOUNT    4509
#define IDC_STATIC_CUR_AREACTRL_SYSWIN  4510
#define IDC_RADIO_AREACTRL_LONG         4511
#define IDC_RADIO_AREACTRL_PING         4512
#define IDC_RADIO_AREACTRL_HU           4513
#define IDC_RADIO_AREACTRL_SYS_LOST     4514
#define IDC_RADIO_AREACTRL_SYS_WIN      4515
#define IDC_COMBO_AREACTRL_TIMES        4516
#define IDC_BUTTON_AREACTRL             4517
#define IDC_BUTTON_CANCEL_AREACTRL      4518
#define IDC_EDIT_FOCUS_PLAYER_GAMEID    4519
#define IDC_BUTTON_ADD_FOCUS_PLAYER     4520
#define IDC_LIST_FOCUS_PLAYER           4521
#define IDC_BUTTON_DELETE_FOCUS_PLAYER  4522
#define IDC_STATIC_ADVANCED_ONLINE_PLAYER 4523
#define IDC_STATIC_ADVANCED_INSCORE_PLAYER 4524
#define IDC_CHECK_ADVANCED_HIDE_AI_INSCORE 4525
#define IDC_COMBO_SEL_PLAYER_TYPE       4526
#define IDC_LIST_USER_BET               4527
#define IDC_LIST_SYSCTRL_TRACELOG       4600
#define IDC_LIST_ROOMCTRL_TRACELOG      4601
#define IDC_LIST_AREACTRL_TRACELOG      4602
#define IDC_STATIC_TRACELOG_BEGIN_RECORDTIME 4603

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3305
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3326
#define _APS_NEXT_SYMED_VALUE           3305
#endif
#endif
