//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ClientDebug.rc 使用
//
#define IDD_DIALOG_MAIN                 3100
#define IDD_CUSTOM_GENERAL              3101
#define IDD_CUSTOM_ADVANCED             3102
#define IDD_CUSTOM_TRACELOG             3103
#define IDC_STATIC_SHOW                 3104
#define IDC_TAB_CUSTOM                  3105
#define IDC_EDIT_STATISTIC_SYSWIN       4000
#define IDC_EDIT_STATISTIC_SERVICE      4001
#define IDC_STATIC_CUR_ANCHOU_RATE      4002
#define IDC_EDIT_CONFIG_ANCHOU_RATE     4003
#define IDC_STATIC_CUR_ANCHOU_TOTAL     4004
#define IDC_BUTTON_ANCHOU               4005
#define IDC_STATIC_CUR_SYSCTRL_SYSSTORAGE 4014
#define IDC_STATIC_CUR_SYSCTRL_PLAYERSTORAGE 4015
#define IDC_STATIC_CUR_SYSCTRL_PARAMETER_K 4016
#define IDC_STATIC_CUR_SYSCTRL_SYSSTORAGE_RESETRATE 4017
#define IDC_STATIC_CUR_SYSCTRL_WINRATE  4018
#define IDC_STATIC_CUR_SYSCTRL_RESETCOUNT 4019
#define IDC_STATIC_CUR_SYSCTRL_SYSWIN   4020
#define IDC_EDIT_CONFIG_SYSCTRL_SYSSTORAGE 4021
#define IDC_EDIT_CONFIG_SYSCTRL_PLAYERSTORAGE 4022
#define IDC_EDIT_CONFIG_SYSCTRL_PARAMETER_K 4023
#define IDC_EDIT_CONFIG_SYSCTRL_SYSSTORAGE_RESETRATE 4024
#define IDC_BUTTON_SYSCTRL              4025
#define IDC_STATIC_CUR_ROOMCTRL_SYSSTORAGE 4026
#define IDC_STATIC_CUR_ROOMCTRL_PLAYERSTORAGE 4027
#define IDC_STATIC_CUR_ROOMCTRL_PARAMETER_K 4028
#define IDC_STATIC_CUR_ROOMCTRL_SYSSTORAGE_RESETRATE 4029
#define IDC_STATIC_CUR_ROOMCTRL_WINRATE 4030
#define IDC_EDIT_CONFIG_ROOMCTRL_SYSSTORAGE 4031
#define IDC_EDIT_CONFIG_ROOMCTRL_PLAYERSTORAGE 4032
#define IDC_EDIT_CONFIG_ROOMCTRL_PARAMETER_K 4033
#define IDC_EDIT_CONFIG_ROOMCTRL_SYSSTORAGE_RESETRATE 4034
#define IDC_BUTTON_ROOMCTRL             4035
#define IDC_LIST_CUR_ROOMCTRL_INFO      4036
#define IDC_STATIC_CUR_ROOMCTRL_SYSWIN  4037
#define IDC_BUTTON_CANCEL_ROOMCTRL      4038
#define IDC_EDIT_PLAYER_GAMEID          4500
#define IDC_BUTTON_QUERY_PLAYER_GAMEID  4501
#define IDC_COMBO_TABLECTRL_TIMES        4502
#define IDC_RADIO_TABLECTRL_CURPLAYER_WIN 4503
#define IDC_RADIO_TABLECTRL_CURPLAYER_LOST 4504
#define IDC_RADIO_TABLECTRL_BANKER_WIN   4505
#define IDC_RADIO_TABLECTRL_BANKER_LOST  4506
#define IDC_BUTTON_TABLECTRL             4507
#define IDC_BUTTON_CANCEL_TABLECTRL      4508
#define IDC_STATIC_TABLECTRL_ID          4509
#define IDC_STATIC_TABLECTRL_CURTABLEID  4510
#define IDC_STATIC_TABLECTRL_CURTABLE_BANKERCHAIRID 4511
#define IDC_STATIC_TABLECTRL_CURTABLE_PLAYERCOUNT 4512
#define IDC_STATIC_TABLECTRL_CONFIGCOUNT 4513
#define IDC_STATIC_TABLECTRL_CURCOUNT    4514
#define IDC_STATIC_CUR_TABLECTRL_SYSWIN  4515
#define IDC_LIST_CUR_TABLECTRL_INFO     4516
#define IDC_LIST_SYSCTRL_TRACELOG       4600
#define IDC_LIST_ROOMCTRL_TRACELOG      4601
#define IDC_LIST_TABLECTRL_TRACELOG      4602
#define IDC_STATIC_TRACELOG_BEGIN_RECORDTIME 4603

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3305
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3327
#define _APS_NEXT_SYMED_VALUE           3305
#endif
#endif
