//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ClientControl.rc
//
#define IDC_STATIC_START_STORAGE_TABLE  5002
#define IDC_STATIC_STORAGEINFO_TABLE    5003
#define IDC_STATIC_ROOM_STORAGE_START   5004
#define IDC_STATIC_ROOM_STORAGE_CURRENT 5005
#define IDC_STATIC_SYSTEM_WINLOSE       5006
#define IDC_STATIC_ROOMCONFIG_INFO      5007
#define IDC_BUTTON_UPDATE_STORAGE_TABLE 5008
#define IDC_BUTTON_MODIFY_ROOMCONFIG    5009
#define IDC_STATIC_ROOM_STORAGE_INPUT   5010
#define IDC_BUTTON_ROOM_ADVANCE         5011
#define IDC_STATIC_ROOM_STORAGE_INPUT2  5012
#define IDC_STATIC_SYSTEM_              5012
#define IDC_STATIC_SYSTEM_RECOVER       5012
#define IDD_CLIENT_CONTROL              6000
#define IDC_BTN_USER_BET_QUERY          6015
#define IDC_BT_CONTINUE_WIN             6016
#define IDC_EDIT_CURRENT_STORAGE_TABLE  6017
#define IDC_EDIT_STORAGE_DEDUCT_ROOM    6018
#define IDC_EDIT_STORAGE_MAX1_ROOM      6019
#define IDC_EDIT_STORAGE_MUL1_ROOM      6020
#define IDC_EDIT_STORAGE_MAX2_ROOM      6021
#define IDC_EDIT_STORAGE_MUL2_ROOM      6022
#define IDC_BT_CONTINUE_LOST            6023
#define IDC_BT_CONTINUE_CANCEL          6024
#define IDC_EDIT_GAME_TWO               6025
#define IDC_EDIT_CONTROL_COUNT          6026
#define IDC_EDIT_GAME_THREE             6027
#define IDC_EDIT_USER_ID                6028
#define IDC_RICHEDIT_USERDESCRIPTION    6029
#define IDC_RICHEDIT_USERCONTROL        6030
#define IDC_RICHEDIT_OPERATION_RECORD   6031
#define IDC_STATIC_TABLE_INFO           6032
#define IDC_LIST_ROOMUSER               6033
#define IDC_EDIT_ZHONGJIANG_JIAN        6034
#define IDC_LIST_TABLE_MAP_STORAGE      6035
#define IDC_LIST_TABLE_MAP_STORAGE_ALL  6037
#define IDC_EDIT_TABLEID                6038
#define IDC_EDIT_MODIFY_SINGLETABLE     6039
#define IDC_BUTTON_SINGLEMODE_CONFIRM   6040
#define IDC_EDIT_BATCH_STORAGE          6043
#define IDC_BUTTON_BATCH_CONFIRM        6044
#define IDC_RICHEDIT_BATCH_DESCRIPTION  6045
#define IDC_STATIC_SINGLEMODE_DESCRIPTION 6046
#define IDC_STATIC_BATCH_DESCRIPTION    6047
#define IDC_BUTTON_CONFIRM_SELECTED     6048
#define IDC_BUTTON_DELETE_SELECTED      6049
#define IDC_COMBO_COUNT                 6051
#define IDC_COMBO_TYPE                  6052
#define IDC_RADIO_GAMEID                6053
#define IDC_RADIO_NICKNAME              6054
#define IDC_STATIC_NAME                 6055
#define IDC_STATIC_ZHONG_JIANG          6056
#define IDC_EDIT_ZHONGJIANG             6068
#define IDC_EDIT_GAME_TWO_DEDUCT        6069
#define IDC_EDIT_GAME_THREE_DEDUCT      6070

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6071
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         6058
#define _APS_NEXT_SYMED_VALUE           6001
#endif
#endif
